package Font::TTF::Tags;

=head1 NAME

Font::TTF::Tags - Utilities for TrueType/OpenType tags

=head1 SYNOPSIS

  use Font::TTF::Tags qw( %tttags %ttnames readtagsfile );
  
  # Look at built-in stuff:
  $script_tag = %tttags{'SCRIPT'}{'Cypriot Syllabary'};
  $lang_name = %ttnames{'LANGUAGE'}{'AFK '}
  
  # Read latest tags file to add to built-in definitions
  readtagsfile ("C:\\Program Files\\Microsoft VOLT\\TAGS.txt");
  
First-level keys to %tttags and %ttnames are:

=over

'SCRIPT' -- retrieve script tag or name

'LANGUAGE' -- retrieve language tag or name

'FEATURE' -- retrieve feature tag or name

=back

Built-in data has been derived from Microsoft's tag registry at
L<http://www.microsoft.com/typography/otspec/ttoreg.htm>, 
updated to draft v1.5 of the OpenType Spec.

=head1 METHODS

=cut

use strict;
use vars qw( %tttags %ttnames @EXPORT_OK );
use Exporter qw( import );
@EXPORT_OK = qw( %tttags %ttnames readtagsfile);


%tttags = (
'SCRIPT' => {

# All derived from http://www.microsoft.com/typography/otspec/scripttags.htm

    "Arabic" => "arab",
    "Armenian" => "armn",
    "Balinese" => "bali",
    "Bengali" => "beng",
    "Bengali v.2" => "bng2",
    "Bopomofo" => "bopo",
    "Braille" => "brai",
    "Buginese" => "bugi",
    "Buhid" => "buhd",
    "Byzantine Music" => "byzm",
    "Canadian Syllabics" => "cans",
    "Carian" => "cari",
    "Cham" => "cham",
    "Cherokee" => "cher",
    "CJK Ideographic" => "hani",
    "Coptic" => "copt",
    "Cypriot Syllabary" => "cprt",
    "Cyrillic" => "cyrl",
    "Default" => "DFLT",
    "Deseret" => "dsrt",
    "Devanagari" => "deva",
    "Devanagari v.2" => "dev2",
    "Ethiopic" => "ethi",
    "Georgian" => "geor",
    "Glagolitic" => "glag",
    "Gothic" => "goth",
    "Greek" => "grek",
    "Gujarati" => "gujr",
    "Gujarati v.2" => "gjr2",
    "Gurmukhi" => "guru",
    "Gurmukhi v.2" => "gur2",
    "Hangul" => "hang",
    "Hangul Jamo" => "jamo",
    "Hanunoo" => "hano",
    "Hebrew" => "hebr",
    "Hiragana" => "kana",
    "Javanese" => "java",
    "Kannada" => "knda",
    "Kannada v.2" => "knd2",
    "Katakana" => "kana",
    "Kayah Li" => "kali",
    "Kharosthi" => "khar",
    "Khmer" => "khmr",
    "Lao" => "lao ",
    "Latin" => "latn",
    "Lepcha" => "lepc",
    "Limbu" => "limb",
    "Linear B" => "linb",
    "Lycian" => "lyci",
    "Lydian" => "lydi",
    "Malayalam" => "mlym",
    "Malayalam v.2" => "mlm2",
    "Mathematical Alphanumeric Symbols" => "math",
    "Mongolian" => "mong",
    "Musical Symbols" => "musc",
    "Myanmar" => "mymr",
    "New Tai Lue" => "talu",
    "N'Ko" => "nko ",
    "Ogham" => "ogam",
    "Ol Chiki" => "olck",
    "Old Italic" => "ital",
    "Old Persian Cuneiform" => "xpeo",
    "Oriya" => "orya",
    "Oriya v.2" => "ory2",
    "Osmanya" => "osma",
    "Phags-pa" => "phag",
    "Phoenician" => "phnx",
    "Rejang" => "rjng",
    "Runic" => "runr",
    "Saurashtra" => "saur",
    "Shavian" => "shaw",
    "Sinhala" => "sinh",
    "Sumero-Akkadian Cuneiform" => "xsux",
    "Sundanese" => "sund",
    "Syloti Nagri" => "sylo",
    "Syriac" => "syrc",
    "Tagalog" => "tglg",
    "Tagbanwa" => "tagb",
    "Tai Le" => "tale",
    "Tamil" => "taml",
    "Tamil v.2" => "tml2",
    "Telugu" => "telu",
    "Telugu v.2" => "tel2",
    "Thaana" => "thaa",
    "Thai" => "thai",
    "Tibetan" => "tibt",
    "Tifinagh" => "tfng",
    "Ugaritic Cuneiform" => "ugar",
    "Vai" => "vai ",
    "Yi" => "yi  ",
    }, 

'LANGUAGE' => {
	 "Default" => "dflt",
	 
# The remainder derived from http://www.microsoft.com/typography/otspec/languagetags.htm

    "Abaza" => "ABA ",
    "Abkhazian" => "ABK ",
    "Adyghe" => "ADY ",
    "Afrikaans" => "AFK ",
    "Afar" => "AFR ",
    "Agaw" => "AGW ",
    "Alsatian" => "ALS ",
    "Altai" => "ALT ",
    "Amharic" => "AMH ",
    "Arabic" => "ARA ",
    "Aari" => "ARI ",
    "Arakanese" => "ARK ",
    "Assamese" => "ASM ",
    "Athapaskan" => "ATH ",
    "Avar" => "AVR ",
    "Awadhi" => "AWA ",
    "Aymara" => "AYM ",
    "Azeri" => "AZE ",
    "Badaga" => "BAD ",
    "Baghelkhandi" => "BAG ",
    "Balkar" => "BAL ",
    "Baule" => "BAU ",
    "Berber" => "BBR ",
    "Bench" => "BCH ",
    "Bible Cree" => "BCR ",
    "Belarussian" => "BEL ",
    "Bemba" => "BEM ",
    "Bengali" => "BEN ",
    "Bulgarian" => "BGR ",
    "Bhili" => "BHI ",
    "Bhojpuri" => "BHO ",
    "Bikol" => "BIK ",
    "Bilen" => "BIL ",
    "Blackfoot" => "BKF ",
    "Balochi" => "BLI ",
    "Balante" => "BLN ",
    "Balti" => "BLT ",
    "Bambara" => "BMB ",
    "Bamileke" => "BML ",
    "Bosnian" => "BOS ",
    "Breton" => "BRE ",
    "Brahui" => "BRH ",
    "Braj Bhasha" => "BRI ",
    "Burmese" => "BRM ",
    "Bashkir" => "BSH ",
    "Beti" => "BTI ",
    "Catalan" => "CAT ",
    "Cebuano" => "CEB ",
    "Chechen" => "CHE ",
    "Chaha Gurage" => "CHG ",
    "Chattisgarhi" => "CHH ",
    "Chichewa" => "CHI ",
    "Chukchi" => "CHK ",
    "Chipewyan" => "CHP ",
    "Cherokee" => "CHR ",
    "Chuvash" => "CHU ",
    "Comorian" => "CMR ",
    "Coptic" => "COP ",
    "Cree" => "CRE ",
    "Carrier" => "CRR ",
    "Crimean Tatar" => "CRT ",
    "Church Slavonic" => "CSL ",
    "Czech" => "CSY ",
    "Danish" => "DAN ",
    "Dargwa" => "DAR ",
    "Woods Cree" => "DCR ",
    "German" => "DEU ",
    "Dogri" => "DGR ",
    "Dhivehi (deprecated)" => "DHV ",
    "Dhivehi" => "DIV ",
    "Djerma" => "DJR ",
    "Dangme" => "DNG ",
    "Dinka" => "DNK ",
    "Dari" => "DRI ",
    "Dungan" => "DUN ",
    "Dzongkha" => "DZN ",
    "Ebira" => "EBI ",
    "Eastern Cree" => "ECR ",
    "Edo" => "EDO ",
    "Efik" => "EFI ",
    "Greek" => "ELL ",
    "English" => "ENG ",
    "Erzya" => "ERZ ",
    "Spanish" => "ESP ",
    "Estonian" => "ETI ",
    "Basque" => "EUQ ",
    "Evenki" => "EVK ",
    "Even" => "EVN ",
    "Ewe" => "EWE ",
    "French Antillean" => "FAN ",
    "Farsi" => "FAR ",
    "Finnish" => "FIN ",
    "Fijian" => "FJI ",
    "Flemish" => "FLE ",
    "Forest Nenets" => "FNE ",
    "Fon" => "FON ",
    "Faroese" => "FOS ",
    "French" => "FRA ",
    "Frisian" => "FRI ",
    "Friulian" => "FRL ",
    "Futa" => "FTA ",
    "Fulani" => "FUL ",
    "Ga" => "GAD ",
    "Gaelic" => "GAE ",
    "Gagauz" => "GAG ",
    "Galician" => "GAL ",
    "Garshuni" => "GAR ",
    "Garhwali" => "GAW ",
    "Ge'ez" => "GEZ ",
    "Gilyak" => "GIL ",
    "Gumuz" => "GMZ ",
    "Gondi" => "GON ",
    "Greenlandic" => "GRN ",
    "Garo" => "GRO ",
    "Guarani" => "GUA ",
    "Gujarati" => "GUJ ",
    "Haitian" => "HAI ",
    "Halam" => "HAL ",
    "Harauti" => "HAR ",
    "Hausa" => "HAU ",
    "Hawaiin" => "HAW ",
    "Hammer-Banna" => "HBN ",
    "Hiligaynon" => "HIL ",
    "Hindi" => "HIN ",
    "High Mari" => "HMA ",
    "Hindko" => "HND ",
    "Ho" => "HO  ",
    "Harari" => "HRI ",
    "Croatian" => "HRV ",
    "Hungarian" => "HUN ",
    "Armenian" => "HYE ",
    "Igbo" => "IBO ",
    "Ijo" => "IJO ",
    "Ilokano" => "ILO ",
    "Indonesian" => "IND ",
    "Ingush" => "ING ",
    "Inuktitut" => "INU ",
    "Irish" => "IRI ",
    "Irish Traditional" => "IRT ",
    "Icelandic" => "ISL ",
    "Inari Sami" => "ISM ",
    "Italian" => "ITA ",
    "Hebrew" => "IWR ",
    "Javanese" => "JAV ",
    "Yiddish" => "JII ",
    "Japanese" => "JAN ",
    "Judezmo" => "JUD ",
    "Jula" => "JUL ",
    "Kabardian" => "KAB ",
    "Kachchi" => "KAC ",
    "Kalenjin" => "KAL ",
    "Kannada" => "KAN ",
    "Karachay" => "KAR ",
    "Georgian" => "KAT ",
    "Kazakh" => "KAZ ",
    "Kebena" => "KEB ",
    "Khutsuri Georgian" => "KGE ",
    "Khakass" => "KHA ",
    "Khanty-Kazim" => "KHK ",
    "Khmer" => "KHM ",
    "Khanty-Shurishkar" => "KHS ",
    "Khanty-Vakhi" => "KHV ",
    "Khowar" => "KHW ",
    "Kikuyu" => "KIK ",
    "Kirghiz" => "KIR ",
    "Kisii" => "KIS ",
    "Kokni" => "KKN ",
    "Kalmyk" => "KLM ",
    "Kamba" => "KMB ",
    "Kumaoni" => "KMN ",
    "Komo" => "KMO ",
    "Komso" => "KMS ",
    "Kanuri" => "KNR ",
    "Kodagu" => "KOD ",
    "Korean Old Hangul" => "KOH ",
    "Konkani" => "KOK ",
    "Kikongo" => "KON ",
    "Komi-Permyak" => "KOP ",
    "Korean" => "KOR ",
    "Komi-Zyrian" => "KOZ ",
    "Kpelle" => "KPL ",
    "Krio" => "KRI ",
    "Karakalpak" => "KRK ",
    "Karelian" => "KRL ",
    "Karaim" => "KRM ",
    "Karen" => "KRN ",
    "Koorete" => "KRT ",
    "Kashmiri" => "KSH ",
    "Khasi" => "KSI ",
    "Kildin Sami" => "KSM ",
    "Kui" => "KUI ",
    "Kulvi" => "KUL ",
    "Kumyk" => "KUM ",
    "Kurdish" => "KUR ",
    "Kurukh" => "KUU ",
    "Kuy" => "KUY ",
    "Koryak" => "KYK ",
    "Ladin" => "LAD ",
    "Lahuli" => "LAH ",
    "Lak" => "LAK ",
    "Lambani" => "LAM ",
    "Lao" => "LAO ",
    "Latin" => "LAT ",
    "Laz" => "LAZ ",
    "L-Cree" => "LCR ",
    "Ladakhi" => "LDK ",
    "Lezgi" => "LEZ ",
    "Lingala" => "LIN ",
    "Low Mari" => "LMA ",
    "Limbu" => "LMB ",
    "Lomwe" => "LMW ",
    "Lower Sorbian" => "LSB ",
    "Lule Sami" => "LSM ",
    "Lithuanian" => "LTH ",
    "Luxembourgish" => "LTZ ",
    "Luba" => "LUB ",
    "Luganda" => "LUG ",
    "Luhya" => "LUH ",
    "Luo" => "LUO ",
    "Latvian" => "LVI ",
    "Majang" => "MAJ ",
    "Makua" => "MAK ",
    "Malayalam Traditional" => "MAL ",
    "Mansi" => "MAN ",
    "Mapudungun" => "MAP ",
    "Marathi" => "MAR ",
    "Marwari" => "MAW ",
    "Mbundu" => "MBN ",
    "Manchu" => "MCH ",
    "Moose Cree" => "MCR ",
    "Mende" => "MDE ",
    "Me'en" => "MEN ",
    "Mizo" => "MIZ ",
    "Macedonian" => "MKD ",
    "Male" => "MLE ",
    "Malagasy" => "MLG ",
    "Malinke" => "MLN ",
    "Malayalam Reformed" => "MLR ",
    "Malay" => "MLY ",
    "Mandinka" => "MND ",
    "Mongolian" => "MNG ",
    "Manipuri" => "MNI ",
    "Maninka" => "MNK ",
    "Manx Gaelic" => "MNX ",
    "Mohawk" => "MOH ",
    "Moksha" => "MOK ",
    "Moldavian" => "MOL ",
    "Mon" => "MON ",
    "Moroccan" => "MOR ",
    "Maori" => "MRI ",
    "Maithili" => "MTH ",
    "Maltese" => "MTS ",
    "Mundari" => "MUN ",
    "Naga-Assamese" => "NAG ",
    "Nanai" => "NAN ",
    "Naskapi" => "NAS ",
    "N-Cree" => "NCR ",
    "Ndebele" => "NDB ",
    "Ndonga" => "NDG ",
    "Nepali" => "NEP ",
    "Newari" => "NEW ",
    "Nagari" => "NGR ",
    "Norway House Cree" => "NHC ",
    "Nisi" => "NIS ",
    "Niuean" => "NIU ",
    "Nkole" => "NKL ",
    "N'Ko" => "NKO ",
    "Dutch" => "NLD ",
    "Nogai" => "NOG ",
    "Norwegian" => "NOR ",
    "Northern Sami" => "NSM ",
    "Northern Tai" => "NTA ",
    "Esperanto" => "NTO ",
    "Nynorsk" => "NYN ",
    "Occitan" => "OCI ",
    "Oji-Cree" => "OCR ",
    "Ojibway" => "OJB ",
    "Oriya" => "ORI ",
    "Oromo" => "ORO ",
    "Ossetian" => "OSS ",
    "Palestinian Aramaic" => "PAA ",
    "Pali" => "PAL ",
    "Punjabi" => "PAN ",
    "Palpa" => "PAP ",
    "Pashto" => "PAS ",
    "Polytonic Greek" => "PGR ",
    "Filipino" => "PIL ",
    "Palaung" => "PLG ",
    "Polish" => "PLK ",
    "Provencal" => "PRO ",
    "Portuguese" => "PTG ",
    "Chin" => "QIN ",
    "Rajasthani" => "RAJ ",
    "R-Cree" => "RCR ",
    "Russian Buriat" => "RBU ",
    "Riang" => "RIA ",
    "Rhaeto-Romanic" => "RMS ",
    "Romanian" => "ROM ",
    "Romany" => "ROY ",
    "Rusyn" => "RSY ",
    "Ruanda" => "RUA ",
    "Russian" => "RUS ",
    "Sadri" => "SAD ",
    "Sanskrit" => "SAN ",
    "Santali" => "SAT ",
    "Sayisi" => "SAY ",
    "Sekota" => "SEK ",
    "Selkup" => "SEL ",
    "Sango" => "SGO ",
    "Shan" => "SHN ",
    "Sibe" => "SIB ",
    "Sidamo" => "SID ",
    "Silte Gurage" => "SIG ",
    "Skolt Sami" => "SKS ",
    "Slovak" => "SKY ",
    "Slavey" => "SLA ",
    "Slovenian" => "SLV ",
    "Somali" => "SML ",
    "Samoan" => "SMO ",
    "Sena" => "SNA ",
    "Sindhi" => "SND ",
    "Sinhalese" => "SNH ",
    "Soninke" => "SNK ",
    "Sodo Gurage" => "SOG ",
    "Sotho" => "SOT ",
    "Albanian" => "SQI ",
    "Serbian" => "SRB ",
    "Saraiki" => "SRK ",
    "Serer" => "SRR ",
    "South Slavey" => "SSL ",
    "Southern Sami" => "SSM ",
    "Suri" => "SUR ",
    "Svan" => "SVA ",
    "Swedish" => "SVE ",
    "Swadaya Aramaic" => "SWA ",
    "Swahili" => "SWK ",
    "Swazi" => "SWZ ",
    "Sutu" => "SXT ",
    "Syriac" => "SYR ",
    "Tabasaran" => "TAB ",
    "Tajiki" => "TAJ ",
    "Tamil" => "TAM ",
    "Tatar" => "TAT ",
    "TH-Cree" => "TCR ",
    "Telugu" => "TEL ",
    "Tongan" => "TGN ",
    "Tigre" => "TGR ",
    "Tigrinya" => "TGY ",
    "Thai" => "THA ",
    "Tahitian" => "THT ",
    "Tibetan" => "TIB ",
    "Turkmen" => "TKM ",
    "Temne" => "TMN ",
    "Tswana" => "TNA ",
    "Tundra Nenets" => "TNE ",
    "Tonga" => "TNG ",
    "Todo" => "TOD ",
    "Turkish" => "TRK ",
    "Tsonga" => "TSG ",
    "Turoyo Aramaic" => "TUA ",
    "Tulu" => "TUL ",
    "Tuvin" => "TUV ",
    "Twi" => "TWI ",
    "Udmurt" => "UDM ",
    "Ukrainian" => "UKR ",
    "Urdu" => "URD ",
    "Upper Sorbian" => "USB ",
    "Uyghur" => "UYG ",
    "Uzbek" => "UZB ",
    "Venda" => "VEN ",
    "Vietnamese" => "VIT ",
    "Wa" => "WA  ",
    "Wagdi" => "WAG ",
    "West-Cree" => "WCR ",
    "Welsh" => "WEL ",
    "Wolof" => "WLF ",
    "Tai Lue" => "XBD ",
    "Xhosa" => "XHS ",
    "Yakut" => "YAK ",
    "Yoruba" => "YBA ",
    "Y-Cree" => "YCR ",
    "Yi Classic" => "YIC ",
    "Yi Modern" => "YIM ",
    "Chinese Hong Kong" => "ZHH ",
    "Chinese Phonetic" => "ZHP ",
    "Chinese Simplified" => "ZHS ",
    "Chinese Traditional" => "ZHT ",
    "Zande" => "ZND ",
    "Zulu" => "ZUL ",
    },

'FEATURE' => {
	 "Default Processing" => "dflt",
	 "Diphthongs" => "dpng",

# The remainder derived from http://www.microsoft.com/typography/otspec/featuretags.htm

    "Access All Alternates" => "aalt",
    "Above-base Forms" => "abvf",
    "Above-base Mark Positioning" => "abvm",
    "Above-base Substitutions" => "abvs",
    "Alternative Fractions" => "afrc",
    "Akhands" => "akhn",
    "Below-base Forms" => "blwf",
    "Below-base Mark Positioning" => "blwm",
    "Below-base Substitutions" => "blws",
    "Contextual Alternates" => "calt",
    "Case-Sensitive Forms" => "case",
    "Glyph Composition / Decomposition" => "ccmp",
    "Conjunct Form After Ro" => "cfar",
    "Conjunct Forms" => "cjct",
    "Contextual Ligatures" => "clig",
    "Centered CJK Punctuation" => "cpct",
    "Capital Spacing" => "cpsp",
    "Contextual Swash" => "cswh",
    "Cursive Positioning" => "curs",
    "Small Capitals From Capitals" => "c2sc",
    "Petite Capitals From Capitals" => "c2pc",
    "Distances" => "dist",
    "Discretionary Ligatures" => "dlig",
    "Denominators" => "dnom",
    "Expert Forms" => "expt",
    "Final Glyph on Line Alternates" => "falt",
    "Terminal Forms #2" => "fin2",
    "Terminal Forms #3" => "fin3",
    "Terminal Forms" => "fina",
    "Fractions" => "frac",
    "Full Widths" => "fwid",
    "Half Forms" => "half",
    "Halant Forms" => "haln",
    "Alternate Half Widths" => "halt",
    "Historical Forms" => "hist",
    "Horizontal Kana Alternates" => "hkna",
    "Historical Ligatures" => "hlig",
    "Hangul" => "hngl",
    "Hojo Kanji Forms (JIS X 0212-1990 Kanji Forms)" => "hojo",
    "Half Widths" => "hwid",
    "Initial Forms" => "init",
    "Isolated Forms" => "isol",
    "Italics" => "ital",
    "Justification Alternates" => "jalt",
    "JIS78 Forms" => "jp78",
    "JIS83 Forms" => "jp83",
    "JIS90 Forms" => "jp90",
    "JIS2004 Forms" => "jp04",
    "Kerning" => "kern",
    "Left Bounds" => "lfbd",
    "Standard Ligatures" => "liga",
    "Leading Jamo Forms" => "ljmo",
    "Lining Figures" => "lnum",
    "Localized Forms" => "locl",
    "Mark Positioning" => "mark",
    "Medial Forms #2" => "med2",
    "Medial Forms" => "medi",
    "Mathematical Greek" => "mgrk",
    "Mark to Mark Positioning" => "mkmk",
    "Mark Positioning via Substitution" => "mset",
    "Alternate Annotation Forms" => "nalt",
    "NLC Kanji Forms" => "nlck",
    "Nukta Forms" => "nukt",
    "Numerators" => "numr",
    "Oldstyle Figures" => "onum",
    "Optical Bounds" => "opbd",
    "Ordinals" => "ordn",
    "Ornaments" => "ornm",
    "Proportional Alternate Widths" => "palt",
    "Petite Capitals" => "pcap",
    "Proportional Kana" => "pkna",
    "Proportional Figures" => "pnum",
    "Pre-Base Forms" => "pref",
    "Pre-base Substitutions" => "pres",
    "Post-base Forms" => "pstf",
    "Post-base Substitutions" => "psts",
    "Proportional Widths" => "pwid",
    "Quarter Widths" => "qwid",
    "Rakar Forms" => "rkrf",
    "Randomize" => "rand",
    "Required Ligatures" => "rlig",
    "Reph Forms" => "rphf",
    "Right Bounds" => "rtbd",
    "Right-to-left alternates" => "rtla",
    "Ruby Notation Forms" => "ruby",
    "Stylistic Alternates" => "salt",
    "Scientific Inferiors" => "sinf",
    "Optical size" => "size",
    "Small Capitals" => "smcp",
    "Simplified Forms" => "smpl",
    "Stylistic Set 1" => "ss01",
    "Stylistic Set 2" => "ss02",
    "Stylistic Set 3" => "ss03",
    "Stylistic Set 4" => "ss04",
    "Stylistic Set 5" => "ss05",
    "Stylistic Set 6" => "ss06",
    "Stylistic Set 7" => "ss07",
    "Stylistic Set 8" => "ss08",
    "Stylistic Set 9" => "ss09",
    "Stylistic Set 10" => "ss10",
    "Stylistic Set 11" => "ss11",
    "Stylistic Set 12" => "ss12",
    "Stylistic Set 13" => "ss13",
    "Stylistic Set 14" => "ss14",
    "Stylistic Set 15" => "ss15",
    "Stylistic Set 16" => "ss16",
    "Stylistic Set 17" => "ss17",
    "Stylistic Set 18" => "ss18",
    "Stylistic Set 19" => "ss19",
    "Stylistic Set 20" => "ss20",
    "Subscript" => "subs",
    "Superscript" => "sups",
    "Swash" => "swsh",
    "Titling" => "titl",
    "Trailing Jamo Forms" => "tjmo",
    "Traditional Name Forms" => "tnam",
    "Tabular Figures" => "tnum",
    "Traditional Forms" => "trad",
    "Third Widths" => "twid",
    "Unicase" => "unic",
    "Alternate Vertical Metrics" => "valt",
    "Vattu Variants" => "vatu",
    "Vertical Writing" => "vert",
    "Alternate Vertical Half Metrics" => "vhal",
    "Vowel Jamo Forms" => "vjmo",
    "Vertical Kana Alternates" => "vkna",
    "Vertical Kerning" => "vkrn",
    "Proportional Alternate Vertical Metrics" => "vpal",
    "Vertical Alternates and Rotation" => "vrt2",
    "Slashed Zero" => "zero",
    }
);

{
    foreach my $s (qw ( SCRIPT LANGUAGE FEATURE ) )
    {
        map { $ttnames{$s}{$tttags{$s}{$_}} = $_ }  keys %{$tttags{$s}};
    }
}


=head2 readtagsfile ( filename )

Read a file in the syntax of Tags.txt (included with Microsoft VOLT) to obtain additional/replacement tag definitions.

Returns 0 if can't open the file; else 1.

=cut

sub readtagsfile
{
    my $fname = shift;
    open (TAGS, $fname) or return 0;
	my ($what, $name, $tag);
	while (<TAGS>)
	{
		($what, $name, $tag) = (m/"([^"]*)", "([^"]*)", "([^"]*)"/);  #"
		$ttnames{$what}{$tag} = $name;
		$tttags{$what}{$name} = $tag;
	}
	close TAGS;
    return 1;	
}



1;
